/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FeaturesSection: typeof import('./src/components/home/FeaturesSection.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HeroSection: typeof import('./src/components/home/HeroSection.vue')['default']
    HomeNavbar: typeof import('./src/components/HomeNavbar.vue')['default']
    IconFacebook: typeof import('./src/components/icons/IconFacebook.vue')['default']
    IconInstagram: typeof import('./src/components/icons/IconInstagram.vue')['default']
    IconTwitter: typeof import('./src/components/icons/IconTwitter.vue')['default']
    JoinSection: typeof import('./src/components/home/JoinSection.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PricingSection: typeof import('./src/components/home/PricingSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  }
}
